sudo: required
language: c

cache:
  apt: true
  directories:
    - mk/.cache

env:
  global:
    # Encrypted COVERITY_SCAN_TOKEN
    - secure: KKhG29VpIOr5mq9xHptpDSfFEcSRKB8BX4e5zL0VQNJGkrNAHJ7ba+boHKEmSJJ1fZvHC18XOb886BIsn0i+lFrVymYDR8L8ca3e/k26LktnqMn76ORK1WYkD1fiRg3lX25v/j0TkoLB7pmDnMhZyGzg20675V1sHbl/KCO1LJI=
  matrix:
    - TEMPLATE=arm/am3505
    - TEMPLATE=arm/bpi
    - TEMPLATE=arm/el24d2
    - TEMPLATE=arm/iwave_imx6
    - TEMPLATE=arm/nxt_bt_pnet
    - TEMPLATE=arm/olimex_bluetooth
    - TEMPLATE=arm/omap
    - TEMPLATE=arm/omap-qt
    - TEMPLATE=arm/overo
    - TEMPLATE=arm/qemu
    - TEMPLATE=arm/qt-app
    - TEMPLATE=arm/raspi
    - TEMPLATE=arm/sabrelite
    - TEMPLATE=arm/stm32_dvfs
    - TEMPLATE=arm/stm32f3cube
    - TEMPLATE=arm/stm32_f4
    - TEMPLATE=arm/stm32f4cube
    - TEMPLATE=arm/stm32f4cube_clang
    - TEMPLATE=arm/stm32f7cube
    - TEMPLATE=arm/stm32_modbus
    - TEMPLATE=arm/stm32_vl
    - TEMPLATE=arm/stm32_vl_light
    - TEMPLATE=arm/ti816x
    - TEMPLATE=arm/ti816x-qt
    - TEMPLATE=arm/vexpress-a9
    - TEMPLATE=e2k/monocube
    - TEMPLATE=microblaze/debug
    - TEMPLATE=microblaze/petalogix
    - TEMPLATE=microblaze/qemu
    - TEMPLATE=mips/gnu-duinomite
    - TEMPLATE=mips/qemu
    - TEMPLATE=mips/rt5350
    - TEMPLATE=msp430/exp430g2
    - TEMPLATE=msp430/mspdebug
    - TEMPLATE=multiclet/mcp04
    - TEMPLATE=platform/efm32zg_sk3200/debug
    - TEMPLATE=platform/mesa/integratorcp
    - TEMPLATE=platform/mesa/mesa_imx6
    - TEMPLATE=platform/mesa/mesa_x86_osmesa
    - TEMPLATE=platform/nuklear/arm_qemu
    - TEMPLATE=platform/nuklear/stm32f7
    - TEMPLATE=platform/nuklear/x86_qemu
    - TEMPLATE=platform/pjsip/arm-qemu
    - TEMPLATE=platform/pjsip/stm32f4discovery
    - TEMPLATE=platform/pjsip/x86-qemu
    - TEMPLATE=platform/stm32f3_agents/feather
    - TEMPLATE=platform/stm32f3_sensors/car
    - TEMPLATE=platform/stm32f4_cnc/debug
    - TEMPLATE=platform/stm32f4_cnc/windows
    - TEMPLATE=platform/stm32f4_multibots/nrf24
    - TEMPLATE=platform/stm32f7/stm32f7_discovery
    - TEMPLATE=platform/stm32f7/usb-device
    - TEMPLATE=ppc/qemu
    - TEMPLATE=sparc/greth
    - TEMPLATE=sparc/qemu
    - TEMPLATE=sparc/tsim
    - TEMPLATE=usermode86/debug
    - TEMPLATE=x86/bifferboard
    - TEMPLATE=x86/debug
    - TEMPLATE=x86/dvfs
    - TEMPLATE=x86/qemu
    - TEMPLATE=x86/qt-app
    - TEMPLATE=x86/qt-vnc
    - TEMPLATE=x86/smp
    - TEMPLATE=x86/studp
    - TEMPLATE=x86/test/fs
    - TEMPLATE=x86/test/lang
    - TEMPLATE=x86/test/net
    - TEMPLATE=x86/test/packetdrill
    - TEMPLATE=x86/third_party
    - TEMPLATE=x86/user_apps
    - TEMPLATE=xen/debug

matrix:
  include:
  - env: UNCRUSTIFY
    install:
      - SRC=$PWD/uncrustify INSTALL=$PWD/uncrustify/dist ./scripts/codestyle/install_uncrustify.sh
    before_script:
      - export PATH=$PWD/uncrustify/dist/bin:$PATH
    script:
      - uncrustify -v
      - ./scripts/codestyle/travis_uncrustify.sh

before_script:
  - set -e # make this script fail as soon as any individual command fail
  - sudo modprobe nfsd
  - DOCKER_START_WAIT_TIME_SEC=60 ./scripts/docker/docker_start.sh embox/emdocker-test
  - |
    if [ "${COVERITY_SCAN_BRANCH}" != 1 ]
    then
      function run() { echo -e '$' "${ANSI_GREEN}$@${ANSI_RESET}"; "$@"; }
    else
      function run() { echo "Not running '$@': Coverity scan build"; }
    fi

script:
  - set -e # make this script fail as soon as any individual command fail
  - . ./scripts/docker/docker_rc.sh
  - dr make confload-"$TEMPLATE"
  - run dr make
  - run dr ./scripts/continuous/run.sh "$TEMPLATE"

addons:
  coverity_scan:
    project:
      name: "embox/embox"
      description: "Build submitted via Travis CI"
    notification_email: eldar.abusalimov@gmail.com
    build_command: make
    branch_pattern: coverity

notifications:
  slack:
    secure: XIP8diNjLokES+oeQJtSQLiGAGxvqlBdoKZqccLsOZWtYToDMoNlILAurNI9wCkb1i9TmNbaNYaGqm4h6jbt/+2gOsi6u1Nu4QpTF+g294hqgE4ztxmqcX7JSOGldLxdG+o+eu6D+yUEwFbrBA0WSEVgB26Sd3JQ0jvnxAk4sJw=
    on_success: change
    on_failure: always
